### ISSUE TITLE
Automation of "!d bump" command via the bot 

### ISSUE THREAD

**Issue by A-J-Sarmah** [Variable-Community/Variable-Bot#2]
### Automation of "!d bump" command so that it runs every two hour

"!d bump" command is needed to be run every **two hours** on the "bot-commands" channel so that the server gets a bump on disboard .
Automating this task via the variable bot would save a lot of trouble.

**Comment by himakhaitan** [comment]
As the Disboard doesn't accept commands messaged by another bot. I have found a fix for it. The bot will low ping the MODs every two hours for running this command.

The message automation function is highly configurable and can accept the different queries, message embeds, and channels to put up to automation.
